// v2/frontend/src/components/agenda/AgendaDayColumn.tsx
/**
 * src/components/agenda/AgendaDayColumn.tsx
 * Layer  : Frontend — composants / agenda
 * Role   : Colonne d'un jour de l'agenda (en-tête + grille 07h–24h + slots).
 *          - Drag vertical sur zone vide → ghost slot → émet onCreateSlot
 *          - Click sur slot existant → émet onSlotClick
 *          - Lecture seule pour les visiteurs (isOwner = false)
 * Used by: Agenda
 */

import { useCallback, useEffect, useRef, useState, type CSSProperties } from "react";
import { localIsoToMinutes, localIsoToTime } from "../../lib/slotDateTime";
import type { AgendaDisplaySlot } from "./Agenda";
import AgendaSlot from "./AgendaSlot";

const DAY_START_HOUR = 7;
const TOTAL_HOURS = 17; // 07h → 24h

interface DayInfo {
  name: string;
  date: string;     // "DD/MM"
  fullDate: string; // "YYYY-MM-DD"
}

interface PendingRange {
  date: string;
  start: string; // "HH:MM"
  end: string;
}

interface Props {
  day: DayInfo;
  slots: AgendaDisplaySlot[];
  isOwner: boolean;
  onCreateSlot: (range: PendingRange) => void;
  onDeleteSlot: (slot: AgendaDisplaySlot) => void;
  onSlotClick: (slot: AgendaDisplaySlot) => void;
  onPublicClick?: (date: string, start: string, end: string) => void;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function snapToQuarter(totalMinutes: number): number {
  return Math.round(totalMinutes / 15) * 15;
}

function minutesToIso(minutes: number, fullDate: string): string {
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return `${fullDate}T${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:00`;
}

function computeSlotStyle(start: string, end: string): CSSProperties {
  const startMinutes = localIsoToMinutes(start);
  const endMinutes = localIsoToMinutes(end);
  const dayStartMinutes = DAY_START_HOUR * 60;
  const dayEndMinutes = (DAY_START_HOUR + TOTAL_HOURS) * 60;

  const totalMinutes = dayEndMinutes - dayStartMinutes;
  const topMinutes = Math.max(0, startMinutes - dayStartMinutes);
  const heightMinutes = Math.max(
    0,
    Math.min(endMinutes, dayEndMinutes) - Math.max(startMinutes, dayStartMinutes)
  );

  if (heightMinutes <= 0) return { display: "none" };
  return {
    top: `${(topMinutes / totalMinutes) * 100}%`,
    height: `${(heightMinutes / totalMinutes) * 100}%`,
  };
}

// ---------------------------------------------------------------------------
// Composant
// ---------------------------------------------------------------------------

export default function AgendaDayColumn({ day, slots, isOwner, onCreateSlot, onDeleteSlot, onSlotClick, onPublicClick }: Props) {
  const gridRef = useRef<HTMLDivElement>(null);

  const ghostRef    = useRef<{ start: string; end: string } | null>(null);
  const [ghost, setGhost] = useState<{ start: string; end: string } | null>(null);

  const dragging     = useRef(false);
  const dragStartMin = useRef(0);

  const toMinutes = useCallback((clientY: number): number => {
    if (!gridRef.current) return DAY_START_HOUR * 60;
    const rect = gridRef.current.getBoundingClientRect();
    const y = Math.min(Math.max(clientY - rect.top, 0), rect.height);
    return DAY_START_HOUR * 60 + (y / rect.height) * TOTAL_HOURS * 60;
  }, []);

  const publicDragging = useRef(false);
  const publicDragStartMin = useRef(0);

  const onMouseDown = useCallback(
    (e: React.MouseEvent) => {
      const target = e.target as HTMLElement;
      if (target.closest(".slot")) return;

      if (!isOwner && onPublicClick) {
        const startMin = snapToQuarter(toMinutes(e.clientY));
        publicDragStartMin.current = startMin;
        publicDragging.current = true;

        const iso = minutesToIso(startMin, day.fullDate);
        ghostRef.current = { start: iso, end: iso };
        setGhost({ start: iso, end: iso });
        return;
      }

      if (!isOwner) return;

      const startMin = snapToQuarter(toMinutes(e.clientY));
      dragStartMin.current = startMin;
      dragging.current = true;

      const iso = minutesToIso(startMin, day.fullDate);
      ghostRef.current = { start: iso, end: iso };
      setGhost({ start: iso, end: iso });
    },
    [isOwner, onPublicClick, toMinutes, day.fullDate]
  );

  useEffect(() => {
    const onMove = (e: MouseEvent) => {
      if (publicDragging.current) {
        const currentMin = snapToQuarter(toMinutes(e.clientY));
        const startMin   = Math.min(publicDragStartMin.current, currentMin);
        const endMin     = Math.max(publicDragStartMin.current, currentMin);
        if (endMin - startMin < 15) return;
        const next = {
          start: minutesToIso(Math.max(startMin, DAY_START_HOUR * 60), day.fullDate),
          end:   minutesToIso(Math.min(endMin, (DAY_START_HOUR + TOTAL_HOURS) * 60), day.fullDate),
        };
        ghostRef.current = next;
        setGhost({ ...next });
        return;
      }

      if (!dragging.current) return;

      const currentMin = snapToQuarter(toMinutes(e.clientY));
      const startMin   = Math.min(dragStartMin.current, currentMin);
      const endMin     = Math.max(dragStartMin.current, currentMin);
      if (endMin - startMin < 15) return;

      const next = {
        start: minutesToIso(Math.max(startMin, DAY_START_HOUR * 60), day.fullDate),
        end:   minutesToIso(Math.min(endMin, (DAY_START_HOUR + TOTAL_HOURS) * 60), day.fullDate),
      };
      ghostRef.current = next;
      setGhost({ ...next });
    };

    const onUp = () => {
      if (publicDragging.current) {
        publicDragging.current = false;
        const current = ghostRef.current;
        ghostRef.current = null;
        setGhost(null);
        if (current) {
          const startMinutes = localIsoToMinutes(current.start);
          const endMinutes = localIsoToMinutes(current.end);
          if (endMinutes - startMinutes >= 15) {
            onPublicClick?.(
              day.fullDate,
              localIsoToTime(current.start),
              localIsoToTime(current.end),
            );
          }
        }
        return;
      }

      if (!dragging.current) return;
      dragging.current = false;

      const current = ghostRef.current;
      ghostRef.current = null;
      setGhost(null);

      if (current) {
        const startMinutes = localIsoToMinutes(current.start);
        const endMinutes = localIsoToMinutes(current.end);
        if (endMinutes - startMinutes >= 15) {
          onCreateSlot({
            date:  day.fullDate,
            start: localIsoToTime(current.start),
            end: localIsoToTime(current.end),
          });
        }
      }
    };

    document.addEventListener("mousemove", onMove);
    document.addEventListener("mouseup", onUp);
    return () => {
      document.removeEventListener("mousemove", onMove);
      document.removeEventListener("mouseup", onUp);
    };
  }, [day.fullDate, onCreateSlot, toMinutes]);

  const hourLines = Array.from({ length: TOTAL_HOURS }, (_, i) => i);

  return (
    <div className="flex min-w-[84px] flex-1 flex-col border-r border-eb-layout last:border-r-0 sm:min-w-[104px]">
      {/* En-tête */}
      <div className="flex h-12 shrink-0 flex-col items-center justify-center border-b border-eb-layout bg-eb-page px-1 text-center">
        <span className="text-[12px] font-medium text-eb-text sm:text-[13px]">{day.name}</span>
        <span className="text-[10px] text-eb-muted sm:text-[11px]">{day.date}</span>
      </div>

      {/* Grille */}
      <div
        ref={gridRef}
        className="flex-1 relative"
        style={{ cursor: isOwner || onPublicClick ? "crosshair" : "default" }}
        onMouseDown={onMouseDown}
      >
        {/* Lignes horaires */}
        {hourLines.map((i) => (
          <div key={i} className="absolute w-full border-t border-eb-layout/60"
            style={{ top: `${(i / TOTAL_HOURS) * 100}%` }} />
        ))}

        {/* Ghost slot */}
        {ghost && (
          <div
            className="slot absolute left-0.5 right-0.5 rounded bg-eb-primary/30 pointer-events-none border border-eb-primary/50"
            style={computeSlotStyle(ghost.start, ghost.end)}
          />
        )}

        {/* Slots */}
        {slots.map((slot) => (
          <AgendaSlot
            key={`${slot.type}-${slot.id}`}
            slot={slot}
            isOwner={isOwner}
            style={computeSlotStyle(slot.start, slot.end)}
            onDelete={onDeleteSlot}
            onClick={onSlotClick}
          />
        ))}
      </div>
    </div>
  );
}

// src/components/agenda/AgendaDayColumn.vue
<!-- src/components/agenda/AgendaDayColumn.vue -->
<!-- -------------------------------------------------------------
 Composant : Colonne d’un jour dans l’agenda hebdomadaire
---------------------------------------------------------------

📌 Description :
  - Gère la création fluide d’un “ghost slot” lors d’un clic + drag.
  - Comportement identique aux slots réels :
      • Snap automatique (15 min)
      • Blocage entre 07:00 → 23:59
      • Durée minimale de 15 min
      • Mouvement 1:1 instantané
  - Le ghost reste visible même en dehors de la colonne, bloqué visuellement.

📍 Événements émis :
  - createSlot({ date, start, end }) → ouvre popup prérempli
  - slotMove({ id, newStart, newEnd })
  - slotResize({ id, newStart, newEnd })
  - slotEdit(slot)
  - slotRemove(id)
------------------------------------------------------------- -->

<template>
  <div
    class="flex-1 h-full flex-shrink-0 snap-center border-r border-back flex flex-col relative"
  >
    <!-- 🗓️ En-tête -->
    <div
      class="h-12 flex flex-col items-center justify-center bg-back-100 border-b border-black-600 shrink-0"
    >
      <span class="text-sm font-medium">{{ day.name }}</span>
      <span class="text-xs text-back-500">{{ day.date }}</span>
    </div>

    <!-- 🕒 Grille -->
    <div
      ref="gridRef"
      class="flex-1 grid relative select-none"
      :style="{ gridTemplateRows: 'repeat(' + totalQuarters + ', 1fr)' }"
      @mousedown="onMouseDown"
    >
      <!-- 📍 Lignes horaires -->
      <div
        v-for="(quarter, qIndex) in quarters"
        :key="qIndex"
        class="border-b border-black-600/10 flex items-start justify-center text-[10px] text-back-400"
        :class="{ 'border-black-600': qIndex % 4 === 0 }"
      >
        <span
          v-if="qIndex % 4 === 0"
          class="absolute left-1 text-[10px] opacity-50"
        >
          {{ formatLabel(quarter) }}
        </span>
      </div>

      <!-- 🟥 Ghost slot -->
      <div
        v-if="ghostSlot"
        class="absolute left-1 right-1 bg-red-500/60 rounded p-1 text-[10px] text-white shadow ghost-slot pointer-events-none"
        :style="slotStyle(ghostSlot)"
      >
        {{ formatHour(ghostSlot.start) }} - {{ formatHour(ghostSlot.end) }}
      </div>

      <!-- 🔴 Slots réels -->
      <AgendaSlot
        v-for="slot in slots"
        :key="slot.id + '-' + slot.start"
        :slot="slot"
        :is-admin="isAdmin"
        :slot-style="slotStyle"
        :format-hour="formatHour"
        @edit="$emit('slotEdit', $event)"
        @remove="$emit('slotRemove', $event)"
        @slotMove="onSlotMove"
        @slotResize="onSlotResize"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onBeforeUnmount } from "vue";
import type { Slot } from "../../services/slots";
import AgendaSlot from "./AgendaSlot.vue";

// -------------------------------------------------------------
// Props
// -------------------------------------------------------------
const props = defineProps<{
  day: { name: string; date: string; fullDate: string };
  slots: Slot[];
  isAdmin: boolean;
  slotStyle: (
    slot: Slot | { start: string; end: string }
  ) => Record<string, string>;
  formatHour: (dateString: string) => string;
}>();

const emit = defineEmits<{
  (e: "slotEdit", slot: Slot): void;
  (e: "slotRemove", id: number): void;
  (
    e: "slotMove",
    payload: { id: number; newStart: string; newEnd: string }
  ): void;
  (
    e: "slotResize",
    payload: { id: number; newStart: string; newEnd: string }
  ): void;
  (e: "createSlot", range: { date: string; start: string; end: string }): void;
}>();

// -------------------------------------------------------------
// Constantes & états
// -------------------------------------------------------------
const totalHours = 17;
const totalQuarters = totalHours * 4;
const quarters = Array.from({ length: totalQuarters }, (_, i) => {
  const hour = Math.floor(i / 4) + 7;
  const min = (i % 4) * 15;
  return `${String(hour).padStart(2, "0")}:${String(min).padStart(2, "0")}`;
});

const gridRef = ref<HTMLElement | null>(null);
const ghostSlot = ref<null | { start: string; end: string }>(null);
const isCreating = ref(false);
let dragStart: Date | null = null;

const DAY_START_HOUR = 7;
const DAY_END_HOUR = 24;
const MIN_DURATION_MIN = 15;

// -------------------------------------------------------------
// Utils
// -------------------------------------------------------------
function snapToQuarter(date: Date): Date {
  const min = date.getMinutes();
  const snapped = Math.round(min / 15) * 15;
  date.setMinutes(snapped, 0, 0);
  return date;
}
function toTimeString(date: Date): string {
  return date.toTimeString().slice(0, 5);
}
function formatLabel(hhmm: string) {
  const [h, m] = hhmm.split(":");
  return m === "00" ? `${h}h` : "";
}

// -------------------------------------------------------------
// 📏 Création du ghost slot
// -------------------------------------------------------------
function onMouseDown(event: MouseEvent) {
  if (!props.isAdmin) return;
  if (!gridRef.value) return;

  // ✅ Empêche la création si on clique sur un slot existant
  const target = event.target as HTMLElement;
  if (target.closest(".slot")) return;

  const grid = gridRef.value.getBoundingClientRect();
  const y = Math.min(Math.max(event.clientY - grid.top, 0), grid.height);
  const ratio = y / grid.height;
  const totalMinutes = totalHours * 60;
  const startMinutes = DAY_START_HOUR * 60 + ratio * totalMinutes;

  const start = new Date(`${props.day.fullDate}T00:00`);
  start.setMinutes(startMinutes);

  dragStart = snapToQuarter(start);
  ghostSlot.value = {
    start: dragStart.toISOString(),
    end: dragStart.toISOString(),
  };
  isCreating.value = true;

  document.addEventListener("mousemove", onMouseMove);
  document.addEventListener("mouseup", onMouseUp);
}

function onMouseMove(event: MouseEvent) {
  if (!isCreating.value || !dragStart || !gridRef.value) return;

  const grid = gridRef.value.getBoundingClientRect();
  const y = Math.min(Math.max(event.clientY - grid.top, 0), grid.height);
  const ratio = y / grid.height;
  const totalMinutes = totalHours * 60;
  const currentMinutes = DAY_START_HOUR * 60 + ratio * totalMinutes;

  const current = new Date(`${props.day.fullDate}T00:00`);
  current.setMinutes(currentMinutes);

  const snapped = snapToQuarter(current);
  let newStart = dragStart < snapped ? dragStart : snapped;
  let newEnd = dragStart < snapped ? snapped : dragStart;

  const duration = (newEnd.getTime() - newStart.getTime()) / 60000;
  if (duration < MIN_DURATION_MIN) return;

  // Bloque haut
  if (newStart.getHours() < DAY_START_HOUR) {
    newStart.setHours(DAY_START_HOUR, 0, 0, 0);
    newEnd = new Date(newStart.getTime() + duration * 60000);
  }

  // Bloque bas
  const limitEnd = new Date(`${props.day.fullDate}T23:59`);
  if (newEnd > limitEnd) {
    newEnd = new Date(limitEnd);
    newStart = new Date(newEnd.getTime() - duration * 60000);
  }

  ghostSlot.value = {
    start: snapToQuarter(newStart).toISOString(),
    end: snapToQuarter(newEnd).toISOString(),
  };
}

function onMouseUp() {
  if (!isCreating.value || !ghostSlot.value) return;

  const start = new Date(ghostSlot.value.start);
  const end = new Date(ghostSlot.value.end);

  emit("createSlot", {
    date: props.day.fullDate,
    start: toTimeString(start),
    end: toTimeString(end),
  });

  ghostSlot.value = null;
  isCreating.value = false;
  dragStart = null;

  document.removeEventListener("mousemove", onMouseMove);
  document.removeEventListener("mouseup", onMouseUp);
}

// -------------------------------------------------------------
// 🧩 Propagation des événements enfants
// -------------------------------------------------------------
function onSlotMove(payload: { id: number; newStart: string; newEnd: string }) {
  emit("slotMove", payload);
}
function onSlotResize(payload: {
  id: number;
  newStart: string;
  newEnd: string;
}) {
  emit("slotResize", payload);
}

onBeforeUnmount(() => {
  document.removeEventListener("mousemove", onMouseMove);
  document.removeEventListener("mouseup", onMouseUp);
});
</script>

<style scoped>
.ghost-slot {
  transition: none;
}
</style>
